export const timelineProjects = [
  {
    title: "Digital Design - Incomplete",
    business: "Universidade Federal do Ceará",
    logo: "ufc",
    period: "Mar 2017 - Dec 2020",
    desc: "",
  },
  {
    title: "Vídeo Maker, Designer & Motion Designer",
    business: "Objetivo Concursos",
    logo: "objetivo",
    period: "Jul 2019 - Oct 2021",
    desc: "Idealization, recording and, mainly, edition of calls and viral videos. In addition a digital pieces conception",
  },
  {
    title: "PJ - Front-end Developer",
    business: "WCF Tecnologia da Informação LTDA",
    logo: "wcf",
    period: "Sep 2021 - Apr 2022",
    desc: "New system developer about tax revenue declaration using React.js technology",
  },
  {
    title: "Estage - Front-end Developer",
    business: "STB Desenvolvimento Tecnológico",
    logo: "stb",
    period: "Jan 2022 - Apr 2022",
    desc: "Creating new components, solving bugs and upgrading Front-end in the Traffic Accidents Dashboard called VIDA using the technologies React.js and React Native.",
  },
  {
    title: "PJ - Full-Stack Developer",
    business: "Exit",
    logo: "exit",
    period: "Apr 2022 - Oct 2022",
    desc: "Creation and maintenance of websites and systems using the technologies React.js,HTML, CSS, Javascript, PHP and Wordpress.",
  },
  {
    title: "Freelancer - Front-end Developer",
    business: "Upwork",
    logo: "upwork",
    period: "May 2022 - Jul 2022",
    desc: "Dashboard mobile app redesign with React Native.",
  },  
  {
    title: "Full Time - Full-Stack Developer",
    business: "Peak Studio ",
    logo: "peak",
    period: "Oct 2022 - Jun 2023",
    desc: "Creation and maintenance of websites and systems using the technologies Vtex.io, React.js, HTML, CSS, Javascript, PHP and Wordpress",
  },
];
